### ISSUE TITLE
Patch checkChplInstall to use temp directory

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel-packaging#12]
`checkChplInstall` (called by `make check`) uses `$HOME` to build a Chapel program, which not a valid location when running `pbuild`. We need to apply a patch that will instead use a temp directory for the Debian package.

**Comment by ben-albrecht** [comment]
@mppf -- I think I'll use `$TMPDIR` instead of `~/.chpl`. Does that sound good to you?

**Comment by ben-albrecht** [comment]
I don't see a good reason to not propagate this change upstream as well:

If `$TMPDIR` is set, use this space, otherwise try to create & use the `~/.chpl` directory.

**Comment by mppf** [comment]
AFAIK `$TMPDIR` is normally set by the shell.
Also, presumably there is some reason we weren't just using `/tmp` before - is the `~/` directory more likely to be able to launch from (e.g. with slurm)?

**Comment by awallace-cray** [comment]
My understanding (I forget where it came from) is HOME was used because the odds of SLURM working for make check were thought to be better.

**Comment by awallace-cray** [comment]
Recall, the same make check runs in the Cray module tests.

**Comment by ben-albrecht** [comment]
> Also, presumably there is some reason we weren't just using /tmp before - is the ~/ directory more likely to be able to launch from (e.g. with slurm)?

>My understanding (I forget where it came from) is HOME was used because the odds of SLURM working for make check were thought to be better.

From the original comment:

```
# $HOME/.chpl/ is used instead of something like $TMPDIR (or /tmp) to improve
# the likelihood that multi locale tests will succeed. $HOME tends to be
# consistent and available on all nodes in distributed systems, unlike $TMPDIR
# which tends to be an in-memory filesystem exclusive to each node.
```

Would there be any benefit to optionally supporting `$TMPDIR` for upstream, or do we only want this patch for the Debian package?

**Comment by mppf** [comment]
I would think a lot of things set `TMPDIR` by default. Am I wrong about that?

**Comment by ben-albrecht** [comment]
There must have been a case where using `$TMPDIR` was not working.. can anyone point to that case?

*edit:* That case is when launching multilocale programs with slurm, and `$TMPDIR` points to `/tmp`

**Comment by ben-albrecht** [comment]
The "patch" will pretty much be:

```bash
export CHPL_CHECK_INSTALL_DIR=$TMPDIR
```

I think this can be set in the `rules` file, actually.

**Comment by ben-albrecht** [comment]
Completed with #13
